services:
  db:
    image: mysql:8
    restart: always
    user: root
    secrets:
      - db-root-pw
      - django-db-pw
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db-root-pw
      MYSQL_DATABASE: memecataloger
      MYSQL_USER: django
      MYSQL_PASSWORD_FILE: /run/secrets/django-db-pw
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
    expose:
      - 3306:3306
  
  redis:
    image: redis:7
    ports:
      - 6379:6379
  
  node:
    build:
      context: ./Frontend
    volumes:
      - ./Frontend/src/:/home/front-runner/src
      - ./Frontend/static/:/home/front-runner/static
  
  server:
    build:
      context: .
      secrets:
       - django-db-pw
    secrets:
      - django-db-pw
    environment:
        DB_PW_FILE: /run/secrets/django-db-pw
    volumes:
      - ./MemeCataloger2/:/home/django-server/MemeCataloger2/
      - ./Frontend/:/home/django-server/Frontend/
      - ./api/:/home/django-server/api/
      - ./Sockets/:/home/django-server/Sockets/
      - ./media/:/home/django-server/media/
      
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:

secrets:
  django-db-pw:
    file: ./django-db-pw.txt
  db-root-pw:
    file: ./db-pw.txt
