# Generated by Django 4.0.5 on 2023-08-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageTags',
            new_name='ImageTag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
