# Generated by Django 4.0.5 on 2023-08-13 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_imagetags_imagetag_rename_user_tag_owner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
