# Generated by Django 5.0.6 on 2024-06-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=1400),
        ),
    ]
